version: '3.8'

services:
  frontend:
    image: frontendsaesportes
    build:
      context: "./frontend-sa/"
    ports:
      - "4200:80"
    depends_on:
      - backend
      - rabbitmq-1
    volumes:
      - ./frontend-sa:/usr/share/nginx/html
    networks:
      - saesportes

  backend:
    image: backendsaesportes
    build:
      context: "./backend-sa/WebApi/"
    ports:
      - "47662:80"
    depends_on:
      - rabbitmq-1
    networks:
      - saesportes

  rabbitmq-1:
    image: rabbitmqclientservice
    build:
      context: ./rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - saesportes

networks: 
  saesportes:
    driver: bridge
