version: '3.8'

services:
  frontend:
    build:
      context: ./FrontEnd/frontend-sa
      dockerfile: Dockerfile
    ports:
      - "4200:80"

  backend:
    build:
      context: ./WebApi/WebApi
    ports:
      - "44363:80"
    depends_on:
      - rabbitmq

  rabbitmq:
      build:
        context: ./rabbitmq
        dockerfile: Dockerfile
      ports:
        - "5672:5672"
        - "15672:15672"

